// data.js — Seed editions + configuration constants
// Increment SEED_VERSION whenever seed edition content changes — forces localStorage refresh
export const SEED_VERSION = 4;

export const AREA_COLORS = {
  'Regulations':             '#002B5C',
  'Product Innovation':      '#4A6F8A',
  'Retail Innovation':       '#c9a84c',
  'Competition':             '#C8102E',
  'Supply Chain':            '#5b6770',
  'Other Interesting News':  '#2dccd3',
};

export const ACTION_COLORS = {
  'FYI':            '#5b6770',
  'Assess':         '#c9a84c',
  'Act & Escalate': '#C8102E',
};

export const ACTION_DEFINITIONS = {
  'FYI':            'For your information. No action needed at this stage.',
  'Assess':         'Worth examining before the next planning decision.',
  'Act & Escalate': 'May warrant escalation to senior leadership for further consideration.',
};

export const ACTION_TYPES = ['FYI', 'Assess', 'Act & Escalate'];

export const AREAS_OF_INTEREST = [
  'Regulations',
  'Product Innovation',
  'Retail Innovation',
  'Competition',
  'Supply Chain',
  'Other Interesting News',
];

export const GEOGRAPHIES = [
  'All', 'Saudi Arabia', 'UAE', 'GCC', 'Turkey', 'Egypt',
  'United Kingdom', 'Germany', 'France', 'Italy', 'Spain', 'Poland', 'Pan-Europe',
];

// ─── Edition 1: 20 Apr – 3 May 2026 ──────────────────────────────────────────
export const EDITION_LATEST = {
  id: 'edition-2026-05-03',
  dateRange: '20 Apr – 3 May 2026',
  publishedAt: '2026-05-03T09:00:00Z',
  executiveSummary: 'Chinese brands are accelerating their European manufacturing footprint — Hongqi is in talks to use a Stellantis plant in Spain, and Leapmotor and Stellantis are considering co-developing new platforms. European BEV sales rose 25% in Q1 2026 with March up 42%, while the VW ID Polo at £22k and a Citroën sub-£15k EV signal the affordable segment is arriving faster than most distributors planned. ABC Motors should review its distribution agreements with Chinese brand partners — BYD (Turkey, Egypt), GAC Motor (Egypt, Poland), Farizon (UAE, UK) and Zeekr (Italy) — before local manufacturing becomes a viable option that removes the need for an import-based distributor.',
  sourcesTotal: 11,
  sourcesFetched: 8,
  items: [
    {
      id: 'l-001',
      headline: 'Hongqi eyes Stellantis plant in Spain to fast-track European EV entry',
      source: 'InsideEVs',
      sourceUrl: 'https://insideevs.com/news/794425/hongqi-build-cars-in-europe/',
      publishedAt: '2026-04-30',
      geographies: ['Spain', 'Pan-Europe'],
      areasOfInterest: ['Competition', 'Regulations'],
      summary: 'Hongqi, China\'s state prestige brand, is in discussions to manufacture vehicles at a Stellantis plant in Spain as a route into the European market that avoids Chinese import tariffs. Local production would sidestep the EU\'s 38% tariff on Chinese-made EVs and give Hongqi a cost structure comparable to European brands.',
      relevance: 5,
      actionType: 'Act & Escalate',
      actionText: 'ABC Motors should review whether its Chinese brand distribution agreements remain viable if those brands establish local manufacturing in the markets ABC serves.',
      soWhat: 'ABC Motors should review its distribution agreements with Chinese brand partners — BYD (Turkey, Egypt), GAC Motor (Egypt, Poland), Farizon (UAE, UK) and Zeekr (Italy) — to confirm whether those agreements hold if partner brands establish local manufacturing and no longer need an import-based distributor.',
      factCheck: { confidence: 'High', flag: false, note: 'Passes all automated checks.' },
      csoReview: { verdict: 'Keep', reason: 'Names a specific ABC business unit with a concrete, actionable implication.' },
    },
    {
      id: 'l-002',
      headline: 'Leapmotor and Stellantis consider co-developing new vehicle platforms',
      source: 'Autocar',
      sourceUrl: 'https://www.autocar.co.uk/car-news/new-cars/leapmotor-and-stellantis-considering-co-developing-new-platforms',
      publishedAt: '2026-04-28',
      geographies: ['Pan-Europe'],
      areasOfInterest: ['Competition', 'Supply Chain'],
      summary: 'Leapmotor and its European partner Stellantis are in discussions to jointly develop new EV platforms, deepening their partnership beyond the existing distribution arrangement. Co-developed platforms would give Leapmotor European engineering credibility while giving Stellantis low-cost EV architecture for mass-market models.',
      relevance: 4,
      actionType: 'Assess',
      actionText: 'ABC Motors should assess how platform co-development between Chinese and European manufacturers changes the cost base for Chinese EVs in markets where ABC distributes these brands.',
      soWhat: 'ABC Motors should factor the declining cost base for Chinese EVs into pricing assumptions for BYD in Turkey and Egypt, and for GAC Motor in Egypt — as Chinese-European platform co-development reduces production costs, the pricing margins on Chinese brands ABC distributes will compress and distribution economics will need to be renegotiated.',
      factCheck: { confidence: 'High', flag: false, note: 'Passes all automated checks.' },
      csoReview: { verdict: 'Keep', reason: 'Names a specific ABC business unit with a concrete, actionable implication.' },
    },
    {
      id: 'l-003',
      headline: 'Jaecoo 7 — China\'s \'Temu Range Rover\' — outsells US, Japanese and Korean rivals in UK',
      source: 'The Guardian',
      sourceUrl: 'https://www.theguardian.com/business/2026/may/01/jaecoo-7-china-electric-car-chery-price-temu-range-rover',
      publishedAt: '2026-05-01',
      geographies: ['United Kingdom', 'Pan-Europe'],
      areasOfInterest: ['Competition', 'Retail Innovation'],
      summary: 'The Jaecoo 7, made by Chinese automaker Chery, has overtaken Toyota, Hyundai and Kia models in UK sales rankings by offering loaded specifications at a price point established rivals cannot match. The car is generating mass-market consumer demand for Chinese SUVs in a market where Chinese brands had previously been marginal.',
      relevance: 5,
      actionType: 'Act & Escalate',
      actionText: 'ABC Motors Turkey and Egypt should track Chinese mass-market SUV launches in their markets — the Jaecoo 7 formula of high specification at a disruptive price is now being replicated by multiple Chinese brands targeting the same segments.',
      soWhat: 'ABC Motors Egypt and Turkey should assess whether the Chinese brands they distribute — BYD and GAC Motor in Egypt, BYD in Turkey — include models positioned against fast-growing affordable Chinese SUVs, or whether a portfolio gap is ceding that segment to competitors not distributed by ABC.',
      factCheck: { confidence: 'High', flag: false, note: 'Passes all automated checks.' },
      csoReview: { verdict: 'Keep', reason: 'Names a specific ABC business unit with a concrete, actionable implication.' },
    },
    {
      id: 'l-004',
      headline: 'Volkswagen ID Polo unveiled at £22k, taking on Renault 5 in entry-level EV segment',
      source: 'Autocar',
      sourceUrl: 'https://www.autocar.co.uk/car-news/electric-cars/revealed-new-volkswagen-id-polo-take-renault-5-%C2%A322k',
      publishedAt: '2026-04-29',
      geographies: ['Pan-Europe', 'United Kingdom'],
      areasOfInterest: ['Product Innovation', 'Competition'],
      summary: 'Volkswagen revealed the ID Polo at £22,000, entering the entry-level EV segment against the Renault 5 and upcoming Kia EV2. The car uses VW\'s MEB Entry platform and is positioned as the affordable EV for European mass-market buyers who cannot stretch to mid-range models.',
      relevance: 4,
      actionType: 'Assess',
      actionText: 'ABC Motors Turkey should request Toyota\'s 2026–2027 EV product roadmap to assess whether a model comparable to the ID Polo is planned for the Turkish market.',
      soWhat: 'ABC Motors Turkey should ask Toyota for its sub-£25k EV pipeline for Turkey — the ID Polo at £22k sets a new price floor in the segment ABC distributes Toyota in, and without a comparable model ABC risks ceding the affordable EV segment to VW and Renault dealers.',
      factCheck: { confidence: 'High', flag: false, note: 'Passes all automated checks.' },
      csoReview: { verdict: 'Keep', reason: 'Names a specific ABC business unit with a concrete, actionable implication.' },
    },
    {
      id: 'l-005',
      headline: 'Citroën targets sub-£15k EV to give \'buying power back\' to European consumers',
      source: 'Autocar',
      sourceUrl: 'https://www.autocar.co.uk/car-news/electric-cars/citro%C3%ABn-give-buying-power-back-europe-sub-%C2%A315k-ev',
      publishedAt: '2026-04-30',
      geographies: ['Pan-Europe', 'France'],
      areasOfInterest: ['Product Innovation', 'Competition'],
      summary: 'Citroën confirmed it is developing an EV priced below £15,000 for European markets, targeting first-time EV buyers and urban drivers who have been priced out of the segment. The move follows Dacia\'s Spring success and responds to consumer demand surveys showing price as the primary barrier to EV adoption.',
      relevance: 3,
      actionType: 'FYI',
      actionText: 'ABC Motors Turkey should monitor the sub-£15k EV segment as a leading indicator for when affordable EVs become mainstream in Turkey, where ABC distributes both Toyota and BYD.',
      soWhat: 'ABC Motors Egypt and Morocco should note the Citroën sub-£15k milestone as a proxy — the Chinese supply chains producing these affordable European EVs are the same ones supplying BYD and MG in ABC\'s MENA markets, and equivalent pricing pressure will reach Egypt and Morocco within 18–24 months.',
      factCheck: { confidence: 'High', flag: false, note: 'Passes all automated checks.' },
      csoReview: { verdict: 'Keep', reason: 'Names a specific ABC business unit with a concrete, actionable implication.' },
    },
    {
      id: 'l-006',
      headline: 'European BEV sales rose 25% in Q1 2026, with March up 42% year-on-year',
      source: 'Best Selling Cars Blog',
      sourceUrl: 'https://www.best-selling-cars.com/europe/2026-q1-europe-battery-electric-car-sales-by-european-country/',
      publishedAt: '2026-04-23',
      geographies: ['Pan-Europe'],
      areasOfInterest: ['Product Innovation', 'Regulations'],
      summary: 'Battery-electric car sales across Europe (EU, EFTA, UK) increased 25% in Q1 2026, with March recording a 42% year-on-year rise. Norway, the Netherlands and Germany led volume growth, while the UK recorded its strongest ever Q1 BEV share at 19.8% of new registrations.',
      relevance: 4,
      actionType: 'Assess',
      actionText: 'ABC Motors Turkey should revise its Toyota BEV order volumes for H2 2026 given the acceleration in European EV demand that will affect Turkish consumer expectations.',
      soWhat: 'ABC Motors Turkey should revise its H2 2026 Toyota BEV orders upward — Q1 European BEV growth at 25% and March at 42% signals demand inflecting in Turkey\'s peer markets, and front-loading orders now avoids supply constraints as Toyota shifts production priority toward EV models.',
      factCheck: { confidence: 'High', flag: false, note: 'Passes all automated checks.' },
      csoReview: { verdict: 'Keep', reason: 'Names a specific ABC business unit with a concrete, actionable implication.' },
    },
    {
      id: 'l-007',
      headline: 'UK car production down 8.2% in March as SMMT warns of challenging outlook',
      source: 'SMMT',
      sourceUrl: 'https://www.smmt.co.uk/car-production-stabilises-but-outlook-still-challenging/',
      publishedAt: '2026-04-30',
      geographies: ['United Kingdom'],
      areasOfInterest: ['Supply Chain', 'Regulations'],
      summary: 'UK vehicle production fell 8.2% year-on-year in March 2026, with 72,511 units built. SMMT cited trade uncertainty and weak export demand as the primary causes, while noting that collaboration with global manufacturing partners will be crucial for the UK industry to regain competitiveness.',
      relevance: 3,
      actionType: 'FYI',
      actionText: 'Automotive Aftermarket\'s LKW Teile division should assess whether UK production softness creates a near-term parts demand opportunity as dealers extend service intervals on existing fleet.',
      soWhat: 'Automotive Aftermarket\'s LKW Teile division should review its UK parts inventory positioning — lower vehicle production typically shifts dealer focus toward aftermarket servicing, and LKW Teile\'s European truck parts network is well placed to capture that near-term demand increase.',
      factCheck: { confidence: 'High', flag: false, note: 'Passes all automated checks.' },
      csoReview: { verdict: 'Keep', reason: 'Names a specific ABC business unit with a concrete, actionable implication.' },
    },
    {
      id: 'l-008',
      headline: 'Leapmotor B05 first drive: China\'s Golf-class hatch earns credibility in Europe',
      source: 'Autocar',
      sourceUrl: 'https://www.autocar.co.uk/car-news/electric-cars/leapmotor-b05-first-drive-chinas-golf-shows-signs-promise',
      publishedAt: '2026-04-28',
      geographies: ['Pan-Europe'],
      areasOfInterest: ['Competition', 'Product Innovation'],
      summary: 'Autocar drove the Leapmotor B05 — a Golf-class Chinese hatchback sold through Stellantis dealerships in Europe — and found it competitive on specification and refinement at its price point. The review marks the first time a credible European automotive title has rated a Leapmotor product as a genuine Golf-class alternative.',
      relevance: 4,
      actionType: 'Assess',
      actionText: 'ABC Motors Turkey should add the Leapmotor B05 to its competitive intelligence briefings, as a Chinese Golf-class EV earning credibility in European press is a signal of rising consumer expectations in Turkey.',
      soWhat: 'ABC Motors Turkey and Egypt should brief their BYD distribution teams on the B05 benchmark — as Leapmotor earns Golf-class credibility in European reviews, that quality standard will migrate to consumer expectations in Turkey and Egypt, raising the bar for BYD models ABC distributes in both markets.',
      factCheck: { confidence: 'High', flag: false, note: 'Passes all automated checks.' },
      csoReview: { verdict: 'Keep', reason: 'Names a specific ABC business unit with a concrete, actionable implication.' },
    },
    {
      id: 'l-009',
      headline: 'VW considers importing Chinese-market cars to Europe to boost competitiveness',
      source: 'Autocar',
      sourceUrl: 'https://www.autocar.co.uk/car-news/new-cars/volkswagen-eyes-chinese-market-cars-europe-boost-competitiveness',
      publishedAt: '2026-04-30',
      geographies: ['Pan-Europe', 'Germany'],
      areasOfInterest: ['Competition', 'Supply Chain'],
      summary: 'Volkswagen is exploring whether to import models developed for the Chinese market into Europe to improve competitiveness against Chinese brands on price and specification. The move would mark a structural reversal — a European OEM using Chinese product development rather than European designs with Chinese manufacturing.',
      relevance: 3,
      actionType: 'FYI',
      actionText: 'ABC Motors should note the VW China-import strategy as evidence that Chinese product cycles now set the competitive benchmark in European markets.',
      soWhat: 'ABC Motors should share the VW China-import news with its confirmed Chinese brand partners — BYD (Turkey, Egypt), GAC Motor (Egypt, Poland) and Farizon (UAE, UK) — as VW validating Chinese-engineered products for European consumers strengthens the market acceptance case for the brands ABC distributes in its own markets.',
      factCheck: { confidence: 'High', flag: false, note: 'Passes all automated checks.' },
      csoReview: { verdict: 'Keep', reason: 'Names a specific ABC business unit with a concrete, actionable implication.' },
    },
    {
      id: 'l-010',
      headline: 'UAE departs OPEC as Iran faces economic pressure from US-led energy blockade',
      source: 'Bloomberg',
      sourceUrl: 'https://www.bloomberg.com/news/videos/2026-05-02/uae-departs-opec-as-iran-feel-economic-sting-of-blockade-video',
      publishedAt: '2026-05-02',
      geographies: ['UAE', 'GCC'],
      areasOfInterest: ['Other Interesting News', 'Regulations'],
      summary: 'The UAE has formally departed OPEC, citing strategic divergence over production targets. The decision coincides with increasing economic pressure on Iran from a US-coordinated blockade. Energy market analysts expect the UAE\'s departure to accelerate its transition from oil production to investment diversification, including in mobility and technology sectors.',
      relevance: 3,
      actionType: 'Assess',
      actionText: 'ABC Motors should assess whether the UAE\'s post-OPEC energy strategy accelerates the government fleet electrification timeline and what that means for the Farizon commercial EV agreement.',
      soWhat: 'ABC Motors should brief its UAE Farizon distribution team on the post-OPEC energy policy direction — a UAE government fleet electrification push would create an immediate volume opportunity for the Farizon commercial EV distribution agreement ABC has announced in the market.',
      factCheck: { confidence: 'High', flag: false, note: 'Passes all automated checks.' },
      csoReview: { verdict: 'Keep', reason: 'Names a specific ABC business unit with a concrete, actionable implication.' },
    },
  ],
};

// ─── Edition 2: 6 Apr – 19 Apr 2026 ─────────────────────────────────────────
export const EDITION_PREV = {
  id: 'edition-2026-04-19',
  dateRange: '6 Apr – 19 Apr 2026',
  publishedAt: '2026-04-19T09:00:00Z',
  executiveSummary: 'The Beijing Motor Show dominated the fortnight with 252 new car launches — Chinese automakers are now producing new models at a pace European and Japanese brands structurally cannot match. EU policy tightened on truck CO2 charges and biofuel sourcing, adding near-term cost pressure for fleet operators in ABC\'s European markets. The most immediate concern is Saudi Arabia: Lucid Motors, 60% owned by the PIF, appointed a new CEO and secured fresh Uber investment, raising the prospect of a state-backed premium EV brand entering KSA retail before ABC\'s Lexus strategy has been updated to respond.',
  sourcesTotal: 11,
  sourcesFetched: 5,
  items: [
    {
      id: 'p-001',
      headline: 'Lucid Motors appoints new CEO and secures additional investment from Uber and Saudi PIF',
      source: 'TechCrunch',
      sourceUrl: 'https://techcrunch.com/2026/04/14/lucid-motors-names-new-ceo-lands-more-money-from-uber-and-saudis/',
      publishedAt: '2026-04-14',
      geographies: ['Saudi Arabia'],
      areasOfInterest: ['Competition', 'Other Interesting News'],
      summary: 'Lucid Motors named a new CEO after a year-long search following Peter Rawlinson\'s resignation, and simultaneously announced fresh investment from both Uber and Saudi Arabia\'s Public Investment Fund. The PIF, which owns 60% of Lucid, continues to back the brand as a strategic EV asset for Saudi Arabia\'s Vision 2030 industrial diversification.',
      relevance: 4,
      actionType: 'Act & Escalate',
      actionText: 'ABC Motors should brief its KSA leadership on the Lucid CEO appointment and request a briefing from Toyota on its Saudi premium EV strategy before Lucid opens its first KSA retail locations.',
      soWhat: 'ABC Motors should escalate the PIF-Lucid development to its KSA management team — a state-backed competitor with government-facilitated retail access entering the Saudi premium segment is a direct threat to the Lexus franchise and warrants a response before the new CEO sets distribution strategy.',
      factCheck: { confidence: 'High', flag: false, note: 'Passes all automated checks.' },
      csoReview: { verdict: 'Keep', reason: 'Names a specific ABC business unit with a concrete, actionable implication.' },
    },
    {
      id: 'p-002',
      headline: 'EU to phase out soy biofuels from renewable energy targets by 2030',
      source: 'ICCT',
      sourceUrl: 'https://theicct.org/european-union-to-phase-out-soy-biofuels-from-renewable-energy-targets-by-2030/',
      publishedAt: '2026-04-13',
      geographies: ['Pan-Europe'],
      areasOfInterest: ['Regulations'],
      summary: 'The European Commission confirmed that soy-based biofuels will be phased out of EU renewable energy targets by 2030, narrowing the range of fuels that qualify for compliance credit under the Renewable Energy Directive. Fleet operators and fuel suppliers in EU markets will need to pivot to alternative compliant fuels, adding cost pressure to commercial vehicle operations.',
      relevance: 3,
      actionType: 'FYI',
      actionText: 'Automotive Aftermarket should flag the biofuel phase-out to its fleet customer contacts in European markets.',
      soWhat: 'Automotive Aftermarket should brief its European fleet service clients on the 2030 soy biofuel deadline — commercial vehicle operators in ABC\'s European markets who rely on soy-blend compliance will need to requalify their fuel sourcing before the deadline.',
      factCheck: { confidence: 'High', flag: false, note: 'Passes all automated checks.' },
      csoReview: { verdict: 'Keep', reason: 'Names a specific ABC business unit with a concrete, actionable implication.' },
    },
    {
      id: 'p-003',
      headline: 'EU road tolls and CO2 charges increase total cost of truck ownership across member states',
      source: 'ICCT',
      sourceUrl: 'https://theicct.org/road-tolls-and-co2-charges-impact-on-the-total-cost-of-ownership-of-trucks-in-europe-apr26/',
      publishedAt: '2026-04-15',
      geographies: ['Pan-Europe', 'Germany', 'France', 'Poland'],
      areasOfInterest: ['Regulations', 'Supply Chain'],
      summary: 'ICCT analysis shows EU road tolls combined with new CO2-based surcharges are materially increasing total cost of ownership for heavy trucks across member states, with Germany and France recording the highest cost increases. The combined burden is expected to accelerate fleet operators\' shift toward zero-emission trucks ahead of 2030 mandates.',
      relevance: 3,
      actionType: 'FYI',
      actionText: 'Automotive Aftermarket\'s LKW Teile division should brief its European fleet clients on the CO2 cost impact and position LKW Teile parts as a cost-reduction lever ahead of the 2030 mandate.',
      soWhat: 'Automotive Aftermarket\'s LKW Teile division should use the rising CO2 truck cost data in its European client conversations — fleet operators facing higher operating costs are more likely to extend existing truck service intervals, which directly expands the addressable market for LKW Teile\'s parts distribution.',
      factCheck: { confidence: 'High', flag: false, note: 'Passes all automated checks.' },
      csoReview: { verdict: 'Keep', reason: 'Names a specific ABC business unit with a concrete, actionable implication.' },
    },
    {
      id: 'p-004',
      headline: 'Beijing Motor Show: 252 new cars across 17 halls signal Chinese output pace',
      source: 'Autocar',
      sourceUrl: 'https://www.autocar.co.uk/opinion/motor-shows-beijing-motor-show/17-halls-252-new-cars-%E2%80%93-and-my-little-pony-what-i-learned',
      publishedAt: '2026-04-27',
      geographies: ['Pan-Europe'],
      areasOfInterest: ['Competition', 'Product Innovation'],
      summary: 'The 2026 Beijing Motor Show featured 252 new car launches across 17 halls, with Chinese domestic brands accounting for the majority of debuts. Autocar\'s correspondent described the scale as incomparable with any European or North American motor show, noting that Chinese brands are now producing new models at a cadence that Western OEMs structurally cannot match.',
      relevance: 4,
      actionType: 'Assess',
      actionText: 'ABC Motors should assess which Beijing Show launches from its confirmed brand partners — BYD, GAC Motor, Farizon and Zeekr — are targeted at export markets and likely to reach ABC\'s distribution markets within 18 months.',
      soWhat: 'ABC Motors should request export roadmaps from BYD (Turkey, Egypt), GAC Motor (Egypt, Poland), Farizon (UAE, UK) and Zeekr (Italy) following the Beijing Show — with 252 new models launched, the pipeline of China-origin vehicles heading to markets ABC operates in is accelerating faster than ABC\'s current distribution agreements are structured to absorb.',
      factCheck: { confidence: 'High', flag: false, note: 'Passes all automated checks.' },
      csoReview: { verdict: 'Keep', reason: 'Names a specific ABC business unit with a concrete, actionable implication.' },
    },
    {
      id: 'p-005',
      headline: 'Leapmotor targets GTI buyers with hot version of B05 hatch at Beijing Show',
      source: 'Autocar',
      sourceUrl: 'https://www.autocar.co.uk/car-news/motor-shows-beijing-motor-show/leapmotor-goes-after-gti-hot-version-new-b05-hatch',
      publishedAt: '2026-04-27',
      geographies: ['Pan-Europe'],
      areasOfInterest: ['Product Innovation', 'Competition'],
      summary: 'Leapmotor unveiled a performance variant of the B05 hatchback at the Beijing Motor Show, targeting buyers of the Volkswagen Golf GTI and similar hot hatches. The car will be sold through Stellantis dealerships in Europe, using the same distribution infrastructure as the standard B05.',
      relevance: 3,
      actionType: 'FYI',
      actionText: 'ABC Motors Turkey should note Leapmotor\'s performance segment entry when briefing its Toyota distribution team — Chinese brands moving into the performance segment are a direct price challenge to Toyota GR models.',
      soWhat: 'ABC Motors Turkey should include Leapmotor\'s performance variant in its competitive intelligence for the Turkish market — if Chinese brands occupy the performance hatch segment at lower price points, ABC\'s Toyota GR distribution in Turkey faces new competition from brands with a structurally lower cost base.',
      factCheck: { confidence: 'High', flag: false, note: 'Passes all automated checks.' },
      csoReview: { verdict: 'Keep', reason: 'Names a specific ABC business unit with a concrete, actionable implication.' },
    },
  ],
};

export const SEED_EDITION = EDITION_LATEST;
